language: php
dist: bionic

matrix:
  fast_finish: true
  include:
    - php: "7.2"
      env: TYPO3_VERSION=^9 RUN_SONAR_SCANNER=1
    - php: "7.3"
      env: TYPO3_VERSION=^9

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    token:
      secure: "UKA4xctLnEF8XXzAxl0KYk7AZyUHIOVFId2fMmcX7dUQQE0iOLqEUVBivFi7ZA3X5afT+mr6gOEl0hTxsk8RwGpuBvfetPWO6zs1YwW4dzarzyTCGdTjsmkyeSpa0MlLrCc4fM/Z9RbIVEaALS1P+p65jlGdP63YyH0lNs8BN3brJ/gvPTdt2xxXL03CVdplQkcbd5Z15VHggMXhEuDNfFT9c6kzZ/fsCoxPXOP4vkGgplne3Z//oZ5bi7ntdPBZYdAkR/4vTHIGhmauJcUTobcW3E7o6CgsaDpJ2glu/WVtMFOEtJIv/7aG6/jVnK/D0bzHaKoRRmGJBU4WrH5FX1DKBgBxSvnfqThomMDdrbrsZGq8/+mY2r8IGcFjb5efQBECktTEYp5vVFokt03lCbNwTi4mJY7SKT/1MnM+U835QabTL5LZCvgPgfSflLsQ3pwIyDnF2717+bI69+gnZkW+UTtgV9wOnqkm5FLolsFK8Eg+82YmUoIzX/u4ajOrQxtuFrekC2ihBj/RIs4XivAd7ulNpkceuYIgVNy90OUmSYZy8awG4w8Iu+nw5B+vZZ7zWfh+EfP4s5ModdfkpUR2NSJgl5gxwFqdL2ucsbdrDbTq3mPA7vJOLYT7QnSFePymnHgBebIqrGZvE57RQ1BrkbARL8+3vanzD3mi2T8="

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms-core=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/web

script:
  - find . -name \*.php  ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  - .Build/bin/phpunit -c Tests/phpunit.xml.dist --log-junit .Build/logs/phpunit.xml --coverage-text --coverage-clover .Build/logs/clover.xml
  - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG; fi
