name: Documentation

on:
  push:
    paths:
      - 'Documentation/**'
  pull_request:
    paths:
      - 'Documentation/**'


jobs:
  tests:
    name: Rendering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Documentation renders without warnings
        run: |
          docker run --rm --pull always -v $(pwd):/project \
             ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log
