name: Documentation

on: [ push, pull_request ]

jobs:
  tests:
    name: Rendering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Documentation renders without warnings
        run: |
          docker run --rm --pull always -v $(pwd):/project \
             ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log
